server:
  address: localhost
  port: 8080
  servlet:
    application-display-name: gateway-dynamic-demo

spring:
  datasource: # 数据库及连接池配置
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
    username: root
    password: wbc12125212
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/gateway

management:
  endpoints:
    web:
      exposure:
        include: '*' # 开启所有actuator端点

logging: # 配置输出日志
  level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.http.server.reactive: DEBUG
      org.springframework.web.reactive: DEBUG
      reactive.ipc.netty: DEBUG

mybatis-plus: # mybatis-plus 配置
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.baicheng.gatewaydynamicdemo.handler
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

hystrix: # 熔断器配置
  metrics:
    polling-interval-ms: 2000
    enabled: true


